export const coingeckoCgiId = 'coinshares-gold-and-cryptoassets-index-lite'
export const coingeckoDpiId = 'defipulse-index'
export const coingeckoFliId = 'eth-2x-flexible-leverage-index'
export const coingeckoIndexId = 'index-cooperative'
export const coingeckoMviId = 'metaverse-index'
