name: Unit Tests

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy .env vars
        run: cp .env.prod .env
      - name: Run unit tests
        with:
          test: yarn test
